
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-browsers

    working_directory: ~/aqa-python

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            wget https://bintray.com/qameta/generic/download_file?file_path=io%2Fqameta%2Fallure%2Fallure%2F2.7.0%2Fallure-2.7.0.zip -O allure-2.7.0.zip
            unzip allure-2.7.0.zip
            chmod +x ./allure-2.7.0/bin/allure
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest --reruns=4 --alluredir=allure-results -v -l
      - run:
          name: Generating report
          when: always
          command: |
            . venv/bin/activate
            ./allure-2.7.0/bin/allure generate ./allure-results -o ./test_reports_html/
      - store_artifacts:
          path: ./test_reports_allure/
          destination: test-reports-allure
      - store_test_results:
          path: ./test_reports_allure/
