
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/aqa-python

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pytest phase01/tests/testFibonacci.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
