
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-stretch-browsers

    working_directory: ~/aqa-python

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest -v -l

      - store_artifacts:
          path: test-reports
          destination: test-reports
